name: Submodule Release Workflow

on:
  release:
    types:
      - created

jobs:
  notify-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout submodule code
        uses: actions/checkout@v2

      - name: Notify Main Repository of a Change
        run: |
          # Configurar el token de acceso personal directamente en los comandos de Git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          curl -X POST \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/RafaelRodriguezSanz/project-fullstack/dispatches" \
            -d '{"event_type": "submodule-release"}'
